-- 회원
CREATE SEQUENCE MEMSEQ 
START WITH 1,
INCREMENT BY 1,
NOMAXVALUE
NOCYCLE
NOCACHE;
	
CREATE TABLE MEMBER(
	MEM_NO NUMBER NOT NULL,
	MEM_ID VARCHAR2(20) NOT NULL,
	MEM_PW VARCHAR2(20) NOT NULL,
	MEM_NAME VARCHAR2(100) NOT NULL,
	MEM_EMAIL VARCHAR2(100) NOT NULL,
	MEM_PIC VARCHAR2(100),
	MEM_ENABLED VARCHAR2(2) NOT NULL,
	CONSTRAINT MEMBER_PK PRIMARY KEY(MEM_NO),
	CONSTRAINT MEMBER_UQ_MEM_ID UNIQUE(MEM_ID),
	CONSTRAINT MEMBER_UQ_MEM_NAME UNIQUE(MEM_NAME),
	CONSTRAINT MEMBER_UQ_MEM_EMAIL UNIQUE(MEM_EMAIL),
	CONSTRAINT MEMBER_MEM_ENABLED_CHK CHECK(MYENABLED IN('Y','N'))
);